name: Tetris Tests


on:
  pull_request:
    branches: [ "dev" ]

jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - name: list some versions
        run: | 
          ls -l
          docker --version
          docker images|grep bl3
