name: Tetris Tests


on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  tetris_tests:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - run: ls -l
      - run: echo "hello"
      - run: docker --version